Summary collector
tarantool/metrics pull request #101
Opened 2020-08-21 20:44 UTC by ZolotarevIgor-mail-ru

Linked to #97

Ported from: https://github.com/bmizerany/perks/tree/master/quantile

Based on: https://ieeexplore.ieee.org/document/1410103 (there is small differences between this paper and https://www.cs.rutgers.edu/~muthu/bquant.pdf, e.g. invariant for targeted quantiles and inserting ±inf samples)

Performance: 
- Random unsorted data between 0 and 100, 10^8 samples: about 50 seconds in average vs 120 in #100.
- Sorted sequence, 10^8 samples: 20 seconds vs ~100 in #100

2020-09-04 08:36 UTC, ZolotarevIgor-mail-ru commented
Testing results:
 - Summary validates by promtool
 - Works with prometheus
 - Works with influx
<img width="819" alt="Снимок экрана 2020-08-28 в 21 47 58" src="https://user-images.githubusercontent.com/63460867/92219103-c5de1500-eea2-11ea-97a1-5106369396c3.png">
<img width="1431" alt="Снимок экрана 2020-08-28 в 20 51 56" src="https://user-images.githubusercontent.com/63460867/92219110-c9719c00-eea2-11ea-8600-f98e8d04cb5f.png">
<img width="1421" alt="Снимок экрана 2020-08-28 в 20 52 34" src="https://user-images.githubusercontent.com/63460867/92219112-ca0a3280-eea2-11ea-96d4-4830932706f3.png">
<img width="853" alt="Снимок экрана 2020-08-28 в 21 43 40" src="https://user-images.githubusercontent.com/63460867/92219113-ca0a3280-eea2-11ea-939a-1953dbb70105.png">

2020-09-04 11:28 UTC, lenkis requested changes

2020-09-04 11:28 UTC, lenkis commented on doc/monitoring/api_reference.rst
> +    Registers a new summary. Quantile computation is based on algorithm `"Effective computation of biased quantiles over data streams" <https://ieeexplore.ieee.org/document/1410103>`_
```suggestion
    Registers a new summary. Quantile computation is based on the algorithm `"Effective computation of biased quantiles over data streams" <https://ieeexplore.ieee.org/document/1410103>`_
```

2020-09-04 11:28 UTC, lenkis commented on doc/monitoring/api_reference.rst
> +    :param table objectives: Quantiles to observe in form ``{quantile = error, ... }``.
```suggestion
    :param table objectives: Quantiles to observe in the form ``{quantile = error, ... }``.
```

2020-09-04 11:28 UTC, lenkis commented on doc/monitoring/api_reference.rst
> +        *  ``name .. "_count"`` - A counter holding number of added observations.
```suggestion
        *  ``name .. "_count"`` - A counter holding the number of added observations.
```

2020-09-08 12:46 UTC, lenkis approved these changes

2020-09-09 11:21 UTC, vasiliy-t approved these changes

2020-09-09 11:25 UTC, merged