Add Cartridge issues gauge
tarantool/metrics pull request #144
Opened 2020-11-27 16:01 UTC by ZolotarevIgor-mail-ru

Refactoring of #110 
Closes #109 
Added labels `level`: `critical, warning`
Project structure changed
Tests refactored

2020-11-27 16:21 UTC, DifferentialOrange approved these changes

2020-11-30 08:36 UTC, vasiliy-t requested changes

2020-11-30 08:36 UTC, vasiliy-t commented on doc/monitoring/api_reference.rst
> +    * ``cartridge_issues`` - Amount of `issues <https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.issues/>` across cluster instances
```suggestion
    * ``cartridge_issues`` - Number of `issues <https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.issues/>` across cluster instances
```

2020-11-30 08:36 UTC, vasiliy-t commented on rpm/tarantool-metrics.spec
> +%dir %{luapkgdir}/metrics/default_metrics/cartridge
we should rename files:

metrics/cartridge.lua for module an entry point 
metrics/cartridge/issues.lua for module files

2020-11-30 14:14 UTC, vasiliy-t approved these changes

2020-11-30 14:41 UTC, merged