Memory metrics
tarantool/metrics pull request #154
Opened 2020-12-08 16:55 UTC by ZolotarevIgor-mail-ru

Part of #124 .
Detailed documentation on memory metrics.

2020-12-09 13:09 UTC, vasiliy-t approved these changes

2020-12-09 13:11 UTC, DifferentialOrange requested changes

2020-12-09 13:11 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +This page provides detailed description of metrics from ``tarantool.metrics``.
what  `tarantool.metrics` is?

2020-12-09 14:20 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +Those metrics provide a picture of the whole Tarantool instance.
picture of memory usage by Tarantool process.

2020-12-09 14:28 UTC, opomuc requested changes

2020-12-09 14:28 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +Those metrics provide a picture of the whole Tarantool instance.
```suggestion
Those metrics provide a picture of memory usage by Tarantool process.
```

2020-12-09 14:28 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +To learn more about usage cases, see `this <https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_slab/#box-slab-info>`_
```suggestion
To learn more about use cases, see `this <https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_slab/#box-slab-info>`_
```

2020-12-09 14:28 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_slab_quota_used`` - the amount of memory that is already distributed to the slab allocator
```suggestion
* ``tnt_slab_quota_used`` - the amount of memory that is already reserved by the slab allocator
```

2020-12-09 14:28 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +Those metrics provide information about spaces size.
```suggestion
Those metrics provide specific information about each individual space in Tarantool instance.
```

2020-12-09 16:07 UTC, vasiliy-t approved these changes

2020-12-09 18:43 UTC, opomuc approved these changes

2020-12-09 19:45 UTC, DifferentialOrange requested changes
In-depth description of default metrics is a really good feature and I am personally requested for it in a couple of tickets. But you have removed more metrics than you have added, and I don't think it's good. Moreover, I'm not sure that the old list of default metrics contained all default metrics enabled by this method.

2020-12-10 06:19 UTC, DifferentialOrange requested changes

2020-12-10 06:19 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +  Lua memory is bounded by 1-2 GB per instance. Monitoring of this metric can prevent memory overflow.
Isn't it strictly 2 Gb?

2020-12-10 09:00 UTC, DifferentialOrange approved these changes

2020-12-10 10:07 UTC, merged