docs: network metrics
tarantool/metrics pull request #155
Opened 2020-12-10 10:15 UTC by ZolotarevIgor-mail-ru

Part of #124 .
Detailed documentation on network metrics.

2020-12-10 13:21 UTC, vasiliy-t requested changes

2020-12-10 13:21 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_sent_rps`` - average number of bytes sent per second in the last 5 seconds
I suggest not documenting _rps metrics. it lacks clarity and could be easily derived from _total

2020-12-10 17:12 UTC, vasiliy-t approved these changes

2020-12-10 17:12 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +Each group of metrics also contains ``rps`` metric that present average value of ``total`` for the last 5 seconds.
```suggestion
```

2020-12-10 18:49 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +Each group of metrics also contains ``rps`` metric that present average value of ``total`` for the last 5 seconds.
```suggestion
Each group of metrics contains ``rps`` metric which is a moving average of ``total`` for the last 5 seconds.
```

2020-12-10 18:49 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_sent_total`` - bytes sent from this instance over network since instance start
```suggestion
* ``tnt_net_sent_total`` - bytes sent from this instance over network since start
```

2020-12-10 18:50 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_received_total`` - bytes this instance has received since instance start
```suggestion
* ``tnt_net_received_total`` - bytes this instance has received since start
```

2020-12-10 18:50 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_connections_total`` - number of incoming network connections since instance start
```suggestion
* ``tnt_net_connections_total`` - number of incoming network connections since start
```

2020-12-10 18:50 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_requests_total`` - number of network requests this instance has handled since instance start
```suggestion
* ``tnt_net_requests_total`` - number of network requests this instance has handled since start
```

2020-12-10 18:51 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_net_requests_current`` - number of pending network requests
```suggestion
* ``tnt_net_requests_current`` - amount of pending network requests
```

2020-12-11 12:43 UTC, opomuc approved these changes

2020-12-11 12:48 UTC, vasiliy-t requested changes

2020-12-11 12:48 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +Each group of metrics contains ``rps`` metric which is a moving average of ``total`` for the last 5 seconds.
```suggestion
```

2020-12-11 13:18 UTC, vasiliy-t approved these changes

2020-12-11 13:33 UTC, merged