docs: runtime metrics
tarantool/metrics pull request #157
Opened 2020-12-11 13:42 UTC by ZolotarevIgor-mail-ru

Part of #124 
Detailed description of replication, fibers, runtime, operations and other metrics.

2020-12-13 13:40 UTC, vasiliy-t requested changes

2020-12-13 13:40 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_cfg_listen`` - Tarantool port number
I suggest to not document metrics we are not collecting https://github.com/tarantool/metrics/pull/43/files

2020-12-13 13:40 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +Provides statistics of fibers. If your app creates a lot of fibers, it can be used for monitoring
I suggest to add link to relevant docs sections, e.g. link to fibers

2020-12-13 13:40 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_stats_op_rps`` - number of calls for the last 5 seconds
I suggest to not document _rps metrics at all, it's confusing and it's value could be derived from _total

2020-12-13 13:40 UTC, vasiliy-t commented on doc/monitoring/metrics_reference.rst
> +mechanism in Tarantool, see `this <https://www.tarantool.io/en/doc/2.6/book/replication/repl_architecture/#replication-mechanism>`_
we should discuss with docs team how not to hardcode links to internal docs sections.

2020-12-14 15:47 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_info_uptime`` – time since server was started, in seconds
server or instance?

2020-12-14 15:49 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_fiber_csw`` - averall fibers context switches number
```suggestion
* ``tnt_fiber_csw`` - averall amount of fibers context switches
```

2020-12-15 09:11 UTC, vasiliy-t approved these changes

2020-12-15 09:36 UTC, opomuc approved these changes

2020-12-15 09:38 UTC, merged