docs: cartridge issues, luajit and cpu metrics in details
tarantool/metrics pull request #159
Opened 2020-12-15 09:49 UTC by ZolotarevIgor-mail-ru

Cartridge metrics moved to metrics_reference.rst
More detailed explanation of LuaJIT and CPU metrics.

This PR with #155 , #154 and #157 is a final part of #124 and should close #122

2020-12-17 09:34 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``lj_strhash_hit`` - number of strings being interned
inserted?

2020-12-17 09:35 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``lj_strhash_miss`` - total number of strings allocations during the platform lifetime
```suggestion
* ``lj_strhash_miss`` - total number of string allocations during the platform lifetime
```

2020-12-17 09:35 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``lj_gc_total`` - memory currently allocated
current allocated Lua memory?

2020-12-17 09:36 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +  `issues <https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.issues/>`
critical и warning не обязательно связаны с memory used

2020-12-17 09:40 UTC, ZolotarevIgor-mail-ru commented on doc/monitoring/metrics_reference.rst
> +* ``lj_strhash_hit`` - number of strings being interned
https://en.wikipedia.org/wiki/String_interning

2020-12-17 12:43 UTC, opomuc approved these changes

2020-12-17 12:53 UTC, DifferentialOrange requested changes

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +  e.g. memory used ratio > 90%, ``warning`` is problems that should be considering,
are problems

Maybe considered? I don't know how to fix this. What did you try to say?

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +  ``level`` - the level of the issue. ``critical`` level is critical cluster problems,
```suggestion
  ``level`` - the level of the issue. ``critical`` level are critical cluster problems,
```

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +LuaJIT metrics helps to understand Lua GC state. Only in Tarantool 2.6+.
Maybe help? I'm not sure about this

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +* ``lj_strhash_miss`` - total number of string allocations during the platform lifetime
platform?

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +* ``lj_gc_steps_finalize`` - count of incremental GC steps (finalize state)
You should group all GC states metrics together

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_cpu_count`` - the number of processors
processors used? currently used?

2020-12-17 12:53 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +  where ``kind`` is ``user`` or ``system``, ``thread_name`` is ``tarantool`` or
I have heard that Tarantool has 4 threads

2020-12-18 06:33 UTC, DifferentialOrange requested changes

2020-12-18 06:33 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +* ``tnt_cpu_count`` - the number of processors configured by the operating system
I still don't get it clearly. Is it system total number that not related to running Tarantool processes at all?

2020-12-18 06:39 UTC, DifferentialOrange requested changes

2020-12-18 06:39 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +**GC allocations:**
I see that it's literally written `lj_gc_*` here, but in fact it's user-allocated objects, not the objects allocated by garbage collector. Am I missing something?

2020-12-24 05:40 UTC, opomuc commented on doc/monitoring/metrics_reference.rst
> +* ``lj_gc_strnum`` - amount of allocated ``string`` objects
I believe `amount of` is used for uncountable nouns.

for reference: https://dictionary.cambridge.org/ru/%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0/%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F-%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0/amount-of-number-of-or-quantity-of

2020-12-29 12:49 UTC, vasiliy-t approved these changes

2020-12-29 12:51 UTC, DifferentialOrange approved these changes

2020-12-30 07:41 UTC, merged