Add health-check for external balancers
tarantool/metrics pull request #175
Opened 2021-01-23 15:40 UTC by no1seman

In production environments Tarantool Cluster usually has a large number of so called "routers", Tarantool instances that handle input load and it is required to evenly distribute the load. Various load-balancers are used for this, but any load-balancer have to know which "routers" are ready to accept the load at that very moment. Metrics library has a special plugin that creates an http handler that can be used by the load-balancer to check the current state of any Tarantula instance. If the instance is ready to accept the load, it will return a response with a 200 status code, if not, with a 500 status code.

I didn't forget about

- [X] Tests
- [X] Changelog
- [X] Documentation

Close #172

2021-01-25 10:26 UTC, ZolotarevIgor-mail-ru requested changes

2021-01-25 10:26 UTC, ZolotarevIgor-mail-ru commented on metrics-scm-1.rockspec
> +        ['metrics.plugins.health']                       = 'metrics/plugins/health/init.lua',
Переименуй  файл init.lua в health.lua

2021-01-25 10:26 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_health_test.lua
> +    t.assert_equals(resp.status, 200)
Не хватает теста на 500 статус

2021-01-25 10:26 UTC, ZolotarevIgor-mail-ru commented on README.md
> +### Instance health check
Продублируй это в doc/monitoring/getting_started.rst, чтобы на сайте тоже было

2021-01-26 05:18 UTC, no1seman commented on metrics-scm-1.rockspec
> +        ['metrics.plugins.health']                       = 'metrics/plugins/health/init.lua',
plugin file renamed to health.lua

2021-01-26 05:18 UTC, no1seman commented on test/integration/cartridge_health_test.lua
> +    t.assert_equals(resp.status, 200)
Added test for 500

2021-01-26 05:19 UTC, no1seman commented on README.md
> +### Instance health check
Add desc for health handler to doc/monitoring/getting_started.rst

2021-01-26 08:01 UTC, ZolotarevIgor-mail-ru approved these changes

2021-01-26 10:44 UTC, merged