Add zone alias for Tarantool Cartridge 2.4.0
tarantool/metrics pull request #201
Opened 2021-02-22 09:30 UTC by no1seman

What has been done? Why? What problem is being solved?

Added zone label is set for instance to support zones introduced in Tarantool Cartridge 2.4.0

I didn't forget about

- [X] Tests
- [X] Changelog
- [X] Documentation (README and rst)
- [X] Rockspec and rpm spec

Close https://github.com/tarantool/metrics/issues/194

Note: promtool has an issue: https://github.com/prometheus/prometheus/issues/8480 but it doesn't helps.

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru requested changes

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on cartridge/roles/metrics.lua
> +    local self = cartridge.admin_get_servers(box.info.uuid)
Please don't use reserved keyword `self` as a variable name

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on cartridge/roles/metrics.lua
> +    if self and next(self) then
Why `next(self)` and not `self[1]`?

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on cartridge/roles/metrics.lua
> +    local params, err = argparse.parse()
Code duplication is not ok
Please move it to special function
And does it really necessary to call it in both `init` and `apply_config`?

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_role_test.lua
> +    if cartridge_version >= 240 then
Please add `t.skip_if`

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_role_test.lua
> +        -- test change server zone name in runtime
Please split it to different tests

- `test_zone_label_present`
- `test_zone_label_changes_in_runtime`

2021-03-12 09:47 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_role_test.lua
> +    if cartridge_version >= 240 then
https://github.com/tarantool/metrics/blob/a2d783e5b68475a7c88f89b5ea10ce470d8e67fa/test/integration/cartridge_metrics_test.lua#L46

2021-03-15 06:58 UTC, ZolotarevIgor-mail-ru requested changes

2021-03-15 06:58 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_role_test.lua
> +    -- Issues introduced in Cartridge 2.0.2
?

2021-03-15 06:58 UTC, ZolotarevIgor-mail-ru commented on test/integration/cartridge_role_test.lua
> +    t.skip_if(utils.is_version_less(cartridge_version, '2.4.0'), 'Cartridge version is must be v2.0.2 or greater')
Please move `version` to function arguments

2021-03-15 15:34 UTC, RunsFor commented on .github/workflows/test.yml
> +        cartridge: [ "", "1.2.0", "2.1.2", "2.4.0" ]
А может проверить и для [2.5.0 картриджа](https://github.com/tarantool/cartridge/releases/tag/2.5.0) тоже?

2021-03-15 19:07 UTC, no1seman commented on .github/workflows/test.yml
> +        cartridge: [ "", "1.2.0", "2.1.2", "2.4.0" ]
Cartridge 2.5.0 added to test matrix

2021-03-15 19:16 UTC, RunsFor approved these changes
lgtm

2021-03-16 06:28 UTC, ZolotarevIgor-mail-ru approved these changes

2021-03-17 13:09 UTC, vasiliy-t approved these changes

2021-03-17 13:09 UTC, vasiliy-t commented on doc/monitoring/getting_started.rst
> +#. There is an ability in Tarantool Cartridge >= ``'2.4.0'`` to set a zone for each
should we add ref to zone's doc page?

2021-03-17 13:16 UTC, merged