cpu metrics: introduce metrics to gather cpu usage
tarantool/metrics pull request #218
Opened 2021-04-01 16:13 UTC by zwirec

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [x] Changelog
- [x] Documentation (README and rst)
- [x] Rockspec and rpm spec

Close #41

2021-04-01 16:56 UTC, Kasen approved these changes
LGTM

2021-04-01 16:57 UTC, Kasen requested changes
error: Installed (but unpackaged) file(s) found:
371
   /usr/share/tarantool/metrics/default_metrics/tarantool/cpu.lua

RPM build has been broken

2021-04-02 07:45 UTC, Kasen approved these changes
LGTM

2021-04-02 08:03 UTC, filonenko-mikhail commented on metrics/default_metrics/tarantool/cpu.lua
> +    local cpu_time = ss_get_rusage()
in case of error it raises in fiber

2021-04-02 08:04 UTC, filonenko-mikhail commented on metrics/default_metrics/tarantool/cpu.lua
> +        return -1
different return contract

2021-04-02 08:04 UTC, filonenko-mikhail commented on metrics/default_metrics/tarantool/cpu.lua
> +    return {
with this

2021-04-05 09:54 UTC, filonenko-mikhail approved these changes

2021-04-05 09:54 UTC, filonenko-mikhail commented
lgtm

2021-04-05 10:00 UTC, merged