cd: add package deploy workflow
tarantool/metrics pull request #381
Opened 2022-07-07 17:43 UTC by artembo

This workflow is intended to run on a tag push for creating and deploying 
module packages to S3 based repositories. The workflow builds package 
using `packpack` and pushes packages via curl request to rws.tarantool.org

Close #379

2022-07-07 18:01 UTC, artembo commented
Please see dry run of workflow here https://github.com/tarantool/metrics/runs/7238731199?check_suite_focus=true

2022-07-08 07:24 UTC, yngvar-antonsson requested changes

2022-07-08 07:24 UTC, yngvar-antonsson commented on .github/workflows/packaging.yml
> +          PRODUCT_NAME: tarantool-queue
queue?

2022-07-08 07:26 UTC, artembo commented on .github/workflows/packaging.yml
> +          PRODUCT_NAME: tarantool-queue
sorry, copy-paste issue, fixed

2022-07-08 07:27 UTC, yngvar-antonsson approved these changes

2022-07-08 07:28 UTC, merged