Add box.info.synchro & box.info.election metrics
tarantool/metrics pull request #392
Opened 2022-07-25 13:56 UTC by panticonur

Add `box.info.synchro` and` box.info.election` metrics

I didn't forget about

- [ ] Changelog
- [ ] Documentation (README and rst)

Close #374

2022-08-02 11:46 UTC, yngvar-antonsson requested changes

2022-08-02 11:46 UTC, yngvar-antonsson commented on CHANGELOG.md
> +- New metrics `box.info()`:
```suggestion
- New metrics:
```

2022-08-03 10:02 UTC, DifferentialOrange requested changes

2022-08-03 10:02 UTC, DifferentialOrange commented on doc/monitoring/metrics_reference.rst
> +                Possible values:
Well, Prometheus, InfluxDB and Graphite (and most, if not every, metric storages) do not support string metrics. Moreover, such format breaks Prometheus metrics collect (InfluxDB should just skip a single invalid metrics, but it still will make it useless).

2022-08-09 09:21 UTC, yngvar-antonsson approved these changes

2022-08-09 10:46 UTC, merged