Fix summary counter
tarantool/metrics pull request #407
Opened 2022-09-13 00:18 UTC by panticonur

Change last index in summary samples loop.

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation (README and rst)
- [ ] Rockspec and rpm spec

Close #189

2022-09-13 10:25 UTC, yngvar-antonsson requested changes

2022-09-14 07:50 UTC, filonenko-mikhail approved these changes

2022-09-16 09:26 UTC, yngvar-antonsson commented on CHANGELOG.md
> +- Fix summary counter.
```suggestion
- Fix queries in quantile
```

2022-09-16 09:26 UTC, yngvar-antonsson approved these changes

2022-09-16 15:30 UTC, merged